[tox]
envlist = py39,py310,py311,py312,py313,py314
skipdist = True
skip_missing_interpreters = true

[testenv]
allowlist_externals =
    coverage
deps =
    -rrequirements.txt
    -rrequirements-test.txt
commands =
    coverage run -m pytest

[testenv:dev]
basepython = python3.13
usedevelop = True
